### ISSUE TITLE
脚本很实用，感谢

### ISSUE THREAD

**Issue by Tynba** [jgpgtg/aliddns-ipv6#1]

**Comment by jgpgtg** [comment]
弄个Dns或者ddns 的admin的权限就行了，来自手机客户端-------- 原始邮件 --------发件人： TciBan <notifications@github.com>日期： 2020年9月8日周二 16:36收件人： jgpgtg/aliddns-ipv6 <aliddns-ipv6@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [jgpgtg/aliddns-ipv6] 脚本很实用，感谢 (#1)

就是阿里云这个什么Access ID光创建一个子账户是不够的，还需要分配相应的权限😅我被权限卡了半天，希望作者能在简介里写一下

**Comment by TciBan** [comment]
发现一个新问题，如果要解析的域名是根域名的话执行脚本就会报错，说什么ak sk登录错误。但是非跟域名就不会有这个问题。

**Comment by TciBan** [comment]
> 就是阿里云这个什么Access ID光创建一个子账户是不够的，还需要分配相应的权限😅我被权限卡了半天，希望作者能在简介里写一下
